### ISSUE TITLE
PHP 8 Support

### ISSUE THREAD

**Issue by grappler** [wearerequired/digest#21]
Add allowed failure testing for PHP 8 to GitHub Action
```
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        include:
          - php: '8.0'
            wordpress: 'latest'
            experimental: true
```
